CMS/urls.py
from CMS import views
from django.urls import path

urlpatterns = [
    path('', views.index, name="index"),
	path('inicio/busqueda', views.busqueda, name='busqueda'), 
]

Ecommerce/urls.py
from django.urls import path
from Ecommerce import views
from django.conf.urls import url

app_name='Ecommerce'

urlpatterns = [
	url(r'^(?P<slug>[\w-]+)/$', views.dispatch_slug, name="dispatch_slug"),
	path('add_product_cart/', views.add_product_cart, name='add_product_cart'),
]

ShopOnline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('jet/', include('jet.urls', 'jet')), 
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('CMS.urls')),
    path('', include('Ecommerce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

Ecommerce/models.py
from django.db import models
#Import para las imagenes en galleria, si queremos asociar un articulo con más de una imagen
from image_cropping import ImageRatioField 
from easy_thumbnails.files import get_thumbnailer
#Import para el campo de moneda
from djmoney.models.fields import MoneyField
from django.db import models
#Import para texto con formato APP
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from CMS.models import AbstractImage
#from django.contrib.auth.models import User
#from datetime import date
#from django.utils.crypto import get_random_string
from django.template.defaultfilters import slugify

class Slug(models.Model):
    slug = models.SlugField(verbose_name=u'URL friendly', unique=True, blank=True, max_length=255)

    def __str__(self):
        return self.slug

class SEOModel(models.Model):
    meta_title = models.CharField( max_length=140, verbose_name='Meta-Title', blank=True)
    slug = models.OneToOneField(Slug, verbose_name=u'URL friendly', blank=True, null=True, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if not self.id and self.slug_id == None:
            try:
                id = self.__class__.objects.latest("id").id + 1
            except:
                id = 1
            slug = Slug(slug=slugify(self.__str__()))
            qs = Slug.objects.filter(slug=slug)
            if qs.exists():
                slug = Slug(slug=slugify(self.__str__())+"-%s" % str(id))
            else:
                slug = Slug(slug=slugify(self.__str__()))
            slug.save()
                
            self.slug = slug
        super(SEOModel, self).save( *args, **kwargs)
        
    class Meta:
        abstract = True

class Category(SEOModel):
    name = models.CharField(max_length=25, blank=True)
    descripcion = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'Category'
        verbose_name_plural = 'Category'

class Product(SEOModel):
    name = models.CharField(max_length=50, blank=True)
    price = MoneyField(max_digits=14, decimal_places=2, default_currency='EUR')
    text = RichTextUploadingField(verbose_name='Text', null=True, blank=True)
    category = models.ForeignKey(Category, related_name='category', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ProductImage(AbstractImage):
    cropping = ImageRatioField('image', '300x300', verbose_name=u'Visible clipping') 	
    product = models.ForeignKey(Product, related_name='product_images', null=True, on_delete=models.CASCADE)  	
    def get_img(self): 		
        return get_thumbnailer(self.image).get_thumbnail({'size': (300, 300), 'box': self.cropping, 'crop': True, 'detail': True }).url 
    def get_big_img(self):
        return self.image.url

Ecommerce/views.py
from django.shortcuts import render, get_object_or_404, redirect
#importar solo modelos que vayan a usarse.
from .models import Category, Product, Slug
from CMS.models import SocialLink

def dispatch_slug(request, slug):
    categories = Category.objects.all()
    socials_red = SocialLink.objects.all()

    total_items_cart = request.session['total_items'] #Es el número total de items en la cesta

    slug = get_object_or_404(Slug, slug=slug)
    qs = Product.objects.filter(slug=slug)
    if qs.exists():
        product = qs[0]
        first_image = product.product_images.all().first().get_img()
        images = product.product_images.all()
        product_name = product.name
        
        return render(request, "Ecommerce/detail.html", locals())   
    
    qs = Category.objects.filter(slug=slug)
    if qs.exists():
        category = qs[0] #contiene la categoria
        product_and_images = Product.objects.filter(category=category.id)
        category_name = category.name
        cat = True
        return render(request, "CMS/index.html", locals())

def add_product_cart(request):
    print("algo")

Ecommerce/templates/Ecommerce/detail.html
{% extends "CMS/main.html" %}

{% block breadcrum %}
	<li><a href="{% url 'Ecommerce:dispatch_slug' product.slug %}">{{ product_name }}</a></li>
{% endblock %}

{% block content %}

<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- Product main img -->
					<div class="col-md-5 col-md-push-2">
						<div id="product-main-img">
							{% for image in images %}
								<div class="product-preview">
									<img src="{{ image.get_big_img }}" alt="image">
								</div>
							{% endfor %}
						</div>
					</div>
					<!-- /Product main img -->

					<!-- Product thumb imgs -->
					<div class="col-md-2  col-md-pull-5">
						<div id="product-imgs">
							{% for image in images %}
								<div class="product-preview">
									<img src="{{ image.get_img }}" alt="image">
								</div>
							{% endfor %}
						</div>
					</div>
					<!-- /Product thumb imgs -->

					<!-- Product details -->
					<div class="col-md-5">
						<div class="product-details">
							<h2 class="product-name">{{ product.name }}</h2>
							<div>
								<div class="product-rating">
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-o"></i>
								</div>
								<a class="review-link" href="#">10 Review(s) | Add your review</a>
							</div>
							<div>
								<h3 class="product-price">{{ product.price }} <del class="product-old-price">$990.00</del></h3>
								<span class="product-available">In Stock</span>
							</div>
							<p>{{ product.text|safe }}</p>
							<div class="product-options">
								<label>
									Size
									<select class="input-select">
										<option value="0">X</option>
									</select>
								</label>
								<label>
									Color
									<select class="input-select">
										<option value="0">Red</option>
									</select>
								</label>
							</div>

							<div class="add-to-cart">
								<div class="qty-label">
									Qty
									<div class="input-number">
										<input type="number">
										<span class="qty-up">+</span>
										<span class="qty-down">-</span>
									</div>
								</div>
								<form method="POST" action="{% url 'Ecommerce:add_product_cart' %}"> 
									{% csrf_token %}
									<!-- {{ form.as_p }} -->
									<input type="hidden" name="name" value="{{product.name}}">
									<input type="hidden" name="price" value="{{product.price}}">
									<input type="hidden" name="photo" value="{{first_image}}">
									<input type="hidden" name="id" value="{{product.id}}">
									<button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
								</form>
							</div>

							<ul class="product-btns">
								<li><a href="#"><i class="fa fa-heart-o"></i> add to wishlist</a></li>
								<li><a href="#"><i class="fa fa-exchange"></i> add to compare</a></li>
							</ul>

							<ul class="product-links">
								<li>Category:</li>
								<li><a href="#">Headphones</a></li>
								<li><a href="#">Accessories</a></li>
							</ul>

							<ul class="product-links">
								<li>Share:</li>
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
								<li><a href="#"><i class="fa fa-envelope"></i></a></li>
							</ul>

						</div>
					</div>
					<!-- /Product details -->

					<!-- Product tab -->
					<div class="col-md-12">
						<div id="product-tab">
							<!-- product tab nav -->
							<ul class="tab-nav">
								<li class="active"><a data-toggle="tab" href="#tab1">Description</a></li>
								<li><a data-toggle="tab" href="#tab2">Details</a></li>
								<li><a data-toggle="tab" href="#tab3">Reviews (3)</a></li>
							</ul>
							<!-- /product tab nav -->

							<!-- product tab content -->
							<div class="tab-content">
								<!-- tab1  -->
								<div id="tab1" class="tab-pane fade in active">
									<div class="row">
										<div class="col-md-12">
											<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
										</div>
									</div>
								</div>
								<!-- /tab1  -->

								<!-- tab2  -->
								<div id="tab2" class="tab-pane fade in">
									<div class="row">
										<div class="col-md-12">
											<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
										</div>
									</div>
								</div>
								<!-- /tab2  -->

								<!-- tab3  -->
								<div id="tab3" class="tab-pane fade in">
									<div class="row">
										<!-- Rating -->
										<div class="col-md-3">
											<div id="rating">
												<div class="rating-avg">
													<span>4.5</span>
													<div class="rating-stars">
														<i class="fa fa-star"></i>
														<i class="fa fa-star"></i>
														<i class="fa fa-star"></i>
														<i class="fa fa-star"></i>
														<i class="fa fa-star-o"></i>
													</div>
												</div>
												<ul class="rating">
													<li>
														<div class="rating-stars">
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
														</div>
														<div class="rating-progress">
															<div style="width: 80%;"></div>
														</div>
														<span class="sum">3</span>
													</li>
													<li>
														<div class="rating-stars">
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star-o"></i>
														</div>
														<div class="rating-progress">
															<div style="width: 60%;"></div>
														</div>
														<span class="sum">2</span>
													</li>
													<li>
														<div class="rating-stars">
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star-o"></i>
															<i class="fa fa-star-o"></i>
														</div>
														<div class="rating-progress">
															<div></div>
														</div>
														<span class="sum">0</span>
													</li>
													<li>
														<div class="rating-stars">
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star-o"></i>
															<i class="fa fa-star-o"></i>
															<i class="fa fa-star-o"></i>
														</div>
														<div class="rating-progress">
															<div></div>
														</div>
														<span class="sum">0</span>
													</li>
													<li>
														<div class="rating-stars">
															<i class="fa fa-star"></i>
															<i class="fa fa-star-o"></i>
															<i class="fa fa-star-o"></i>
															<i class="fa fa-star-o"></i>
															<i class="fa fa-star-o"></i>
														</div>
														<div class="rating-progress">
															<div></div>
														</div>
														<span class="sum">0</span>
													</li>
												</ul>
											</div>
										</div>
										<!-- /Rating -->

										<!-- Reviews -->
										<div class="col-md-6">
											<div id="reviews">
												<ul class="reviews">
													<li>
														<div class="review-heading">
															<h5 class="name">John</h5>
															<p class="date">27 DEC 2018, 8:0 PM</p>
															<div class="review-rating">
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star-o empty"></i>
															</div>
														</div>
														<div class="review-body">
															<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
														</div>
													</li>
													<li>
														<div class="review-heading">
															<h5 class="name">John</h5>
															<p class="date">27 DEC 2018, 8:0 PM</p>
															<div class="review-rating">
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star-o empty"></i>
															</div>
														</div>
														<div class="review-body">
															<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
														</div>
													</li>
													<li>
														<div class="review-heading">
															<h5 class="name">John</h5>
															<p class="date">27 DEC 2018, 8:0 PM</p>
															<div class="review-rating">
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star-o empty"></i>
															</div>
														</div>
														<div class="review-body">
															<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
														</div>
													</li>
												</ul>
												<ul class="reviews-pagination">
													<li class="active">1</li>
													<li><a href="#">2</a></li>
													<li><a href="#">3</a></li>
													<li><a href="#">4</a></li>
													<li><a href="#"><i class="fa fa-angle-right"></i></a></li>
												</ul>
											</div>
										</div>
										<!-- /Reviews -->

										<!-- Review Form -->
										<div class="col-md-3">
											<div id="review-form">
												<form class="review-form">
													<input class="input" type="text" placeholder="Your Name">
													<input class="input" type="email" placeholder="Your Email">
													<textarea class="input" placeholder="Your Review"></textarea>
													<div class="input-rating">
														<span>Your Rating: </span>
														<div class="stars">
															<input id="star5" name="rating" value="5" type="radio"><label for="star5"></label>
															<input id="star4" name="rating" value="4" type="radio"><label for="star4"></label>
															<input id="star3" name="rating" value="3" type="radio"><label for="star3"></label>
															<input id="star2" name="rating" value="2" type="radio"><label for="star2"></label>
															<input id="star1" name="rating" value="1" type="radio"><label for="star1"></label>
														</div>
													</div>
													<button class="primary-btn">Submit</button>
												</form>
											</div>
										</div>
										<!-- /Review Form -->
									</div>
								</div>
								<!-- /tab3  -->
							</div>
							<!-- /product tab content  -->
						</div>
					</div>
					<!-- /product tab -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->
		

{% endblock %}






	